2024-05-17 15:56:08,579 (46/MainThread) __main__ ERROR      eventloop:811  - error with sql: 'create table if not exists RAW_DATA.DATASETS (\r\n\tCOD_SETCONNECTION\t\t\t\tVARCHAR(10485760),\r\n\tCOD_DATASET\t\t\t\tVARCHAR(10485760),\r\n    COD_TYPE                VARCHAR(10485760),\r\n    COD_MODEL               VARCHAR(10485760),\r\n    COD_TYPE_LOAD_SOURCE    VARCHAR(10485760),\r\n    COD_DATASET_ORIGIN      VARCHAR(10485760),\r\n    COD_DATASET_NAME\t\tVARCHAR(10485760),\r\n\tCOD_DATASET_BUSINESS\tVARCHAR(10485760),\r\n    DESC_BUSINESS_DEFINITION\tVARCHAR(10485760)\r\n    ID_MODEL_RUN                VARCHAR(10485760),\r\n\tDT_MODEL_LOAD               VARCHAR(10485760),\r\n\tDT_LOAD                     VARCHAR(10485760)\r\n);'
Traceback (most recent call last):
  File "eventloop.py", line 755, in run_cli
  File "snowflake/cli/sqlexecute.py", line 491, in run
  File "snowflake/cli/sqlexecute.py", line 574, in execute_normal_sql
  File "snowflake/connector/cursor.py", line 908, in execute
  File "snowflake/connector/errors.py", line 290, in errorhandler_wrapper
  File "snowflake/connector/errors.py", line 345, in hand_to_other_handler
  File "snowflake/connector/errors.py", line 221, in default_errorhandler
snowflake.connector.errors.ProgrammingError: 001003 (42000): SQL compilation error:
syntax error line 11 at position 4 unexpected 'ID_MODEL_RUN'.
syntax error line 11 at position 32 unexpected 'VARCHAR'.
syntax error line 11 at position 39 unexpected '('.
